version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pharma-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pharma-net

 mongo:
    image: mongo:6
    container_name: pharma-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pharma-net
      

  app:
    build: .
    container_name: pharma
    restart: always
    depends_on:
      - db
      - mongo
    ports:
      - "8002:8080"
    environment:
      DB_CONN: "host=pharma-db user=postgres password=postgres dbname=healthcare port=5432 sslmode=disable TimeZone=Asia/Kolkata"
    networks:
      - pharma-net
    command: ["sh", "wait-for-db.sh"]

volumes:
  db_data:
   mongo_data:

networks:
  pharma-net:
    driver: bridge
