version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pharma-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
       - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pharma
    restart: always
    depends_on:
      - db      
    ports:
      - "8009:8080"
    volumes:
      - Pharma:/app/data
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: healthcare    

